name: Run Electric Monitor

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # 缓存 Python 依赖
    - name: Cache pip
      uses: actions/cache@v3
      id: cache-pip
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-

    # 注入 Secrets 到配置文件（不覆盖已有数据）
    - name: Inject secrets into config
      run: |
        sed -i "s/__SECRET_USERNAME__/${{ secrets.USERNAME }}/g" 基础配置.json
        sed -i "s/__SECRET_PASSWORD__/${{ secrets.PASSWORD }}/g" 基础配置.json
        sed -i "s/__SECRET_ROOMVERIFY__/${{ secrets.ROOMVERIFY }}/g" 基础配置.json

    # 安装依赖
    - name: Install dependencies
      if: steps.cache-pip.outputs.cache-hit != 'true'
      run: pip install -r requirements.txt

    # 运行爬虫
    - name: Run crawler
      run: python 电量更新.py

    # 提交更新（包含配置文件）
    - name: Commit results
      if: success()
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add 电量数据.csv
        git add logs/*.log
        git add 基础配置.json
        git commit -m "Auto-update data, logs, and config" || echo "No changes"
        git push