name: Run Electric Monitor

on:
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # 缓存 Python 依赖
    - name: Cache pip
      uses: actions/cache@v3
      id: cache-pip
      with:
        path: |
          ~/.cache/pip
          venv/
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # 注入 Secrets 到配置文件
    - name: Inject secrets into config
      run: |
        sed -i "s/__SECRET_USERNAME__/${{ secrets.USERNAME }}/g" 电费分析/基础配置.json
        sed -i "s/__SECRET_PASSWORD__/${{ secrets.PASSWORD }}/g" 电费分析/基础配置.json
        sed -i "s/__SECRET_ROOMVERIFY__/${{ secrets.ROOMVERIFY }}/g" 电费分析/基础配置.json
        echo "配置验证结果："
        cat 电费分析/基础配置.json

    # 安装依赖
    - name: Install dependencies
      if: steps.cache-pip.outputs.cache-hit != 'true'
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: 测试屏蔽情况
      run: |
        echo "=== 测试443端口 ==="
        curl -Iv https://h5cloud.17wanxiao.com 2>&1 | grep 'Connected'
        echo "=== 测试18443端口 ==="
        nc -zv h5cloud.17wanxiao.com 18443
    # 运行爬虫
    - name: Run crawler
      run: |
        source venv/bin/activate
        python 电费分析/电量更新.py

    # 提交更新
    - name: Commit results
      if: success()
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add 电费分析/电量数据.csv
        git add logs/*.log
        git restore --staged 电费分析/基础配置.json
        git commit -m "Auto-update data and logs" || echo "No changes"
        git push