jobs:
  monitor:
    runs-on: ubuntu-latest
    # 方法 1：全局定义（推荐）
    env:
      ROOMVERIFY: ${{ secrets.ROOMVERIFY }}
    
    steps:
      - uses: actions/checkout@v4

      - name: 缓存 Python 依赖
        uses: actions/cache@v3
        # ...缓存配置保持不变...

      - name: 安装依赖
        if: steps.cache-pip.outputs.cache-hit != 'true'
        run: |
          echo "验证值: $ROOMVERIFY"  # 实际值会被 GitHub 隐藏
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: 运行测试
        run: |
          source venv/bin/activate
          python 测试文件/变量与路径测试.py
        # 方法 2：步骤级定义（如果需要覆盖全局）
        env:
          ROOMVERIFY: ${{ secrets.ROOMVERIFY }}  # 确保名称与 Secrets 完全一致