name: 环境变量与路径测试

on:
  workflow_dispatch:

jobs:
  monitor:
    env:
      ROOMVERIFY: ${{ secrets.ROOMVERIFY }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4


    # 缓存 Python 依赖
    - name: 缓存 Python 依赖
      uses: actions/cache@v3
      id: cache-pip
      with:
        path: |
          ~/.cache/pip
          venv/
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # 安装依赖
    - name: 安装依赖
      if: steps.cache-pip.outputs.cache-hit != 'true'
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

      env: # ✅ 必须在此处或 job 级别定义
        ROOMVERIFY: ${{ secrets.ROOMVERIFY }}

    # 运行测试
    - name: 运行测试
      run: |
        source venv/bin/activate
        python 测试文件/变量与路径测试.py
